---

# Install tasks for Debian family
# -----------------------------------------------------------------------------

- name: 'INSTALL | APT | Install MaxMind GeoIP system prerequisites'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ maxmind_geoip_package_cache_valid_time }}"
  with_items: "{{ maxmind_geoip_system_prerequisites }}"

- name: 'INSTALL | APT | Add MaxMind GeoIP repositories'
  block:
    - name: MaxMind | add key
      ansible.builtin.get_url:
        url: "{{ maxmind_geoip_signing_key}}"
        dest: /etc/apt/keyrings/maxmind.asc
      changed_when: false

    - name: MaxMind | apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/maxmind.asc] https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu {{ ansible_distribution_release }} main"
        state: present

- name: 'INSTALL | APT | Install MaxMind GeoIP packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ maxmind_geoip_package_cache_valid_time }}"
  with_items: "{{ maxmind_geoip_packages }}"

- name: 'INSTALL | CRON | Ensure cron.d directory exists'
  file:
    dest: '/etc/cron.d'
    state: 'directory'
    owner: 'root'
  when: maxmind_geoip_enable_cron | bool

- name: 'INSTALL | CRON | Manage automate GeoIP Update with cron'
  cron:
    name: "geopipupdate"
    state: "{{ maxmind_geoip_enable_cron | bool | ternary('present', 'absent')  }}"
    minute: "{{ maxmind_geoip_cron_minute }}"
    hour: "{{ maxmind_geoip_cron_hour }}"
    weekday: "{{ maxmind_geoip_cron_dow }}"
    user: 'root'
    job: "{{ maxmind_geoip_update_binary }} -f {{ maxmind_geoip_configuration_folder_path }}/geoipupdate.conf"
    cron_file: geoipupdate
