---

# Install tasks for Debian family
# -----------------------------------------------------------------------------

- name: 'INSTALL | APT | Install MaxMind GeoIP system prerequisites'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ maxmind_geoip_package_cache_valid_time }}"
  with_items: "{{ maxmind_geoip_system_prerequisites }}"


- name: 'INSTALL | APT | Manage repositories'
  apt_repository:
    codename: "{{ item.codename | default(omit) }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ maxmind_geoip_repositories }}"


- name: 'INSTALL | APT | Install MaxMind GeoIP packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ maxmind_geoip_package_cache_valid_time }}"
  with_items: "{{ maxmind_geoip_packages }}"

- name: 'INSTALL | CRON | Ensure cron.d directory exists'
  file:
    dest: '/etc/cron.d'
    state: 'directory'
    owner: 'root'
  when: maxmind_geoip_enable_cron | bool

- name: 'INSTALL | CRON | automate GeoIP Update with cron'
  cron:
    name: "geopipupdate"
    minute: "{{ maxmind_geoip_cron_minute }}"
    hour: "{{ maxmind_geoip_cron_hour }}"
    weekday: "{{ maxmind_geoip_cron_dow }}"
    user: 'root'
    job: "{{ maxmind_geoip_update_binary }} -f {{ maxmind_geoip_configuration_folder_path }}/geoipupdate.conf"
    cron_file: geoipupdate
  when: maxmind_geoip_enable_cron | bool
